### ISSUE TITLE
Samsung Galaxy A13 not compatible, 32 bit version?

### ISSUE THREAD

**Issue by asorc** [hikari-no-yume/touchHLE#372] opened 2024-10-10 12:47 UTC
### Describe the feature or issue.

Hello,

Would It be possible to make touchhle compatible with Samsung Galaxy A13? 

It seems that the problem It is that is 32 bit instead of 64 bits, don't know if it's the os, or the hardware. 

I don't know how difficult It is to make It compatible for different OS and/or architectures...

The app is great, that's for sure. Thanks a lot for It. 

Another improvement could be to be able to change the screen settings and to be able to modify the controls if you have the will. 

Again, thank you very much for all.

Regards.

### By submitting this issue, I certify that…

- [X] I understand that linking to, discussing or asking for pirated content is not permitted, and will lead to an immediate ban.
- [X] I understand that “Abandonware” and illegal copies of free games are also pirated content.

**Comment by nighto** [comment] 2024-10-10 12:50
That's probably a clone of #220.

**Comment by nighto** [comment] 2024-10-10 12:50
Though according to https://www.gsmarena.com/samsung_galaxy_a13-11402.php that phone is 64 bit

**Comment by hikari-no-yume** [comment] 2024-10-10 12:51
Duplicate of https://github.com/touchHLE/touchHLE/issues/220. We are not going to support 32-bit Android devices.

**Closed as not planned by hikari-no-yume** 2024-10-10 12:51 UTC

**Comment by hikari-no-yume** [comment] 2024-10-10 12:52
Yes I am not sure why the A13 wouldn't work, it doesn't seem like it's a 32-bit phone, though to know for sure I'd have to look at Google Play services that I don't have access to.

**Comment by hikari-no-yume** [comment] 2024-10-10 12:54
Oh there is a version of it with only 3GB of RAM. That one probably only runs 32-bit apps.

Sorry, we do not want to support these devices. 32-bit-only Android phones should not exist in 2024.

**Comment by asorc** [comment] 2024-10-10 12:54
> That's probably a clone of #220.

Yes, sorry. I didn't see, but I checked all the issues. Thanks.

**Comment by asorc** [comment] 2024-10-10 12:57
I can't install It on a Samsung Galaxy A13. I don't know. The last thing I read is that the OS, Android 13 I believe, it's not compatible.

I can get through the ban of copying file in subfolders of the folder Android.

**Comment by asorc** [comment] 2024-10-10 12:59
> Oh there is a version of it with only 3GB of RAM. That one probably only runs 32-bit apps.
> 
> Sorry, we do not want to support these devices. 32-bit-only Android phones should not exist in 2024.

Mine is 4 GB but I can't install It... Don't know why or how to check It...

**Comment by hikari-no-yume** [comment] 2024-10-10 13:01
Then I guess the 4GB one also has this problem.

If you could get a custom 64-bit Android ROM for your device you might be able to get touchHLE to work, but I cannot provide any help with that and you do it at your own risk. Good luck.

**Comment by asorc** [comment] 2024-10-10 13:27
> Then I guess the 4GB one also has this problem.
> 
> If you could get a custom 64-bit Android ROM for your device you might be able to get touchHLE to work, but I cannot provide any help with that and you do it at your own risk. Good luck.

I have an Ulefone Armor X8 with 4 GB of RAM and I can install on It. I don't know...

**Comment by hikari-no-yume** [comment] 2024-10-10 13:29
It is not about the amount of memory directly; whether the device supports 64-bit apps is ultimately decided by the manufacturer, and they often, but do not always, refuse to support this on devices with less than 4GB of RAM.
