### ISSUE TITLE
Partial loading and playability for several games

### ISSUE THREAD

**Issue by borkleyspook** [hikari-no-yume/touchHLE#115] opened 2023-05-15 03:26 UTC
Tested using the Windows build of touchHLE from [GitHub Actions](https://github.com/hikari-no-yume/touchHLE/actions/runs/4963071042) for commit 16c7fd5:

# Games with a high level of playability: 

## 1. BubbleBash

touchHLE v0.1.2-164-g16c7fd5 (git) — https://touchhle.org/

App bundle info:
- Display name: BubbleBash
- Version: 1.37
- Identifier: com.gameloft.BubbleBash
- Internal name (canonical): BubbleBash.app
- Minimum OS version: 2.2.1

This seems to be very playable. It crashes if you enable music/sound on first load. However, sound effects work if manually enabled from settings. The bottom half of the screen graphically glitches wildly when in the main bubble shooting game. Levels 1-5 are playable of Arcade Mode but it crashes at level 6 and above. The "More Games" option also crashes the emulator. Crab Fever mode also works.

## 2. FastLane

touchHLE v0.1.2-164-g16c7fd5 (git) — https://touchhle.org/

App bundle info:
- Display name: Fastlane
- Version: 1.7
- Identifier: com.atodab.actane
- Internal name (canonical): streetracer.app
- Minimum OS version: 2.1

touchHLE v0.1.2-164-g16c7fd5 (git) — https://touchhle.org/

App bundle info:
- Display name: Fastlane
- Version: 2.0
- Identifier: com.atodab.actane
- Internal name (canonical): streetracer.app
- Minimum OS version: 2.1

Menus seem to mostly work. Racing seems to work properly. Did not test extensively as this game relies on gyroscopic controls which I do not have access to right now.

# Games which have some level of loading or functioning:

## 1. Magic Balls Island: 

touchHLE v0.1.2-164-g16c7fd5 (git) — https://touchhle.org/

App bundle info:
- Display name: Magic Balls Island
- Version: 1.3
- Identifier: Com.ColorboxSoftware.LinesDeluxe
- Internal name (canonical): Magic Balls Island.app
- Minimum OS version: 2.2.1

Loads to a black screen. Crashes when the screen is clicked. 

## 2. BrainChal: 

touchHLE v0.1.2-164-g16c7fd5 (git) — https://touchhle.org/

App bundle info:
- Display name: BrainChal.
- Version: 1.0
- Identifier: com.gameloft.BrainChallenge
- Internal name (canonical): BrainChallenge.app
- Minimum OS version: (not specified)

touchHLE v0.1.2-164-g16c7fd5 (git) — https://touchhle.org/

App bundle info:
- Display name: BrainChal.
- Version: 1.6.1
- Identifier: com.gameloft.BrainChallenge
- Internal name (canonical): BrainChallenge.app
- Minimum OS version: 2.2.1

Game partially loads but crashes before it can be interacted with, with multiple intro screens.

**Comment by hikari-no-yume** [comment] 2023-05-15 08:39
Thanks for the info! I actually knew Fastlane was working because I've been focusing on that game recently: https://social.noyu.me/@hikari/statuses/01H05NECK7C04223VPBCZAN6AA. There's a number of issues with it that I'm hoping to fix before the next release. I don't know about these other titles though. It's great to know some things are starting to work unexpectedly.

**Comment by ghost** [comment] 2023-05-16 03:55
Other info about Bubble Bash:
- The Gameloft logo intro is skipped because it's a MP4.
- The emulator logs appears to have a UIView-related warning: `touchHLE::frameworks::uikit::ui_view: TODO: [(UIView*)0x3000b420 addSubview:0x3000b440]`
Also, here's a screenshot of the glitching:
![image](https://github.com/hikari-no-yume/touchHLE/assets/132712354/4a1f8778-9866-4fc1-bf30-f9f78fcbb061)

**Comment by GamingDuckingalt** [comment] 2023-05-17 13:25
Change the name to "Partial loading and playability for some games"

**Comment by GamingDucking** [comment] 2023-06-03 11:10
Bubble Bash, Brain Challenge, Fastlane and Magic Balls Island is now regressed as of the latest bulid.

**Comment by hikari-no-yume** [comment] 2023-06-05 10:22
@GamingDucking Thanks for letting me know! It seems that I made a mistake in the refactoring I did on Friday (7a6874b16c6e766dd10c372f19c95a09f27cc210), and I hadn't tested Fastlane when I committed it. Without your comment it would have taken longer before I noticed it.

I've fixed this now in 25933af9eb406c96bb9c799c9582373d4ebcbe89.

**Comment by GamingDucking** [comment] 2023-06-05 15:05
Can confirm that it fixed the regressions on the latest build.

**Comment by GamingDucking** [comment] 2023-07-25 16:24
so the recent bulid kinda regressed wolf3d. bulid is https://github.com/hikari-no-yume/touchHLE/commit/23ea3a461614c65649b60ebafc2ce743ba974d8f
![Capture](https://github.com/hikari-no-yume/touchHLE/assets/90236481/6a98015f-8537-40ed-9ad4-58e05c00d174)

**Comment by hikari-no-yume** [comment] 2023-07-25 16:29
To confirm, was it working _for you_ in an earlier build? It still works for me, but I'm using a build of a very early version of the game. Also, what graphics card do you have?

**Comment by GamingDucking** [comment] 2023-07-25 16:54
> To confirm, was it working _for you_ in an earlier build? It still works for me, but I'm using a build of a very early version of the game. Also, what graphics card do you have?

yea, it was working for me yesterday. my graphics card is a Intel IGPU (Intel Graphics 520). Will locate the regression as soon as I can.

**Comment by GamingDucking** [comment] 2023-07-25 16:57
can confirm that the latest bulid did broke wolf3d for me.

**Comment by hikari-no-yume** [comment] 2023-07-25 18:57
Can you narrow it down to a specific build? What's the most recent build that works, and the oldest build that doesn't?

**Comment by GamingDucking** [comment] 2023-07-26 04:29
> Can you narrow it down to a specific build? What's the most recent build that works, and the oldest build that doesn't?

https://github.com/hikari-no-yume/touchHLE/commit/23ea3a461614c65649b60ebafc2ce743ba974d8f: Broken
https://github.com/hikari-no-yume/touchHLE/commit/62ae8c2e17dcf774a91036c53f1a71e77e8ceabe: Working

**Comment by hikari-no-yume** [comment] 2023-07-26 09:14
Huh. Can you specify exactly which version of Wolfenstein 3D you have?

**Comment by hikari-no-yume** [comment] 2023-07-26 09:19
Oh I hadn't noticed that modified splash screen mentioning ZodTTD. Maybe this version is modified from id Software's in some way that causes problems for touchHLE.

**Comment by GamingDucking** [comment] 2023-07-27 03:05
> Oh I hadn't noticed that modified splash screen mentioning ZodTTD. Maybe this version is modified from id Software's in some way that causes problems for touchHLE.

Most likely i got a modified version of the 1.0 version of wolf3d.

**Comment by GamingDucking** [comment] 2023-10-15 10:08
> Other info about Bubble Bash:
> 
>     * The Gameloft logo intro is skipped because it's a MP4.
> 
>     * The emulator logs appears to have a UIView-related warning: `touchHLE::frameworks::uikit::ui_view: TODO: [(UIView*)0x3000b420 addSubview:0x3000b440]`
>       Also, here's a screenshot of the glitching:
>       ![image](https://user-images.githubusercontent.com/132712354/238528660-4a1f8778-9866-4fc1-bf30-f9f78fcbb061.png)

as of https://github.com/hikari-no-yume/touchHLE/commit/8f38f57c60747312fed9ac98c10e72dee3cd7d1b, the glitching problem ingame is fixed, and all game modes are working after testing it.
![2](https://github.com/hikari-no-yume/touchHLE/assets/90236481/b452c3e2-2ea6-4b0f-914d-2fd8dadab26d)

**Comment by hikari-no-yume** [comment] 2023-10-15 10:29
@GamingDucking Thanks for reporting this!

I see from your report at https://appdb.touchhle.org/apps/25 that this game crashes with an “invalid checksum” after level five? I think that means the IPA is corrupted, but if it works fine on real hardware then I wonder if I should make touchHLE tolerate corruption…

**Comment by GamingDucking** [comment] 2023-10-20 14:40
> @GamingDucking Thanks for reporting this!
> 
> I see from your report at https://appdb.touchhle.org/apps/25 that this game crashes with an “invalid checksum” after level five? I think that means the IPA is corrupted, but if it works fine on real hardware then I wonder if I should make touchHLE tolerate corruption…

Tried the same version (dumped from my old Iphone 2) of the game, and its working. Even managed to complete the entire 1st area.
![3](https://github.com/hikari-no-yume/touchHLE/assets/90236481/e67a4a08-86a8-409d-a5e7-a78256068e33)
![4](https://github.com/hikari-no-yume/touchHLE/assets/90236481/00e8fe77-4c6b-44f1-8b7b-0ecbb46928d9)

**Comment by hikari-no-yume** [comment] 2023-10-20 15:40
@GamingDucking Thanks for letting me know! I approved your new report and deleted the old one (because I don't want to keep reports around caused by corrupted files).

**Comment by GamingDucking** [comment] 2023-10-28 12:20
Hey. So, somebody got Cybersaurus (sheva221 made some typos which is Cybersauirus and the screenshot is apparently landscape, but the game is in portrait mode) working. Both v1.6 and v1.65 are kinda working but if i move to another area (there's two areas in the first level), the game crashes with either:
v1.65:
Can't free 0x30396640, unknown allocation! or Can't free 0x303965e0, unknown allocation!
v1.6:
Can't free 0x30397360, unknown allocation! or Can't free 0x30397240, unknown allocation!
![1](https://github.com/hikari-no-yume/touchHLE/assets/90236481/7260d7c3-f5a4-45f0-95e8-da8894882d9d)

**Comment by hikari-no-yume** [comment] 2023-10-28 12:22
@GamingDucking Ah okay, so it's a 3-star rather than 4-star? If you make your own report on that game I can delete theirs.

**Comment by GamingDucking** [comment] 2023-10-28 12:25
> @GamingDucking Ah okay, so it's a 3-star rather than 4-star? If you make your own report on that game I can delete theirs.

Sure. i definitely think that Sheva didn't properly test the game.

**Comment by hikari-no-yume** [comment] 2023-10-28 12:26
Actually if you make a new “app” that's most convenient, then I don't have to manually fix the typo.

**Comment by hikari-no-yume** [comment] 2023-10-29 12:32
@GamingDucking btw: https://appdb.touchhle.org/apps/37

**Comment by Jaffhj** [comment] 2023-10-29 13:01
Head2Head Racing Game is Works

Who is Darxun

**Comment by Jerty56** [comment] 2023-11-25 16:58
Yes is Works Head2Head With 4 Stars
Next New App?

**Comment by ciciplusplus** [comment] 2024-02-18 16:18
Since opening of this issue we now have an app compatibility DB - https://appdb.touchhle.org/
Please report partially working games there, thanks

**Closed as completed by ciciplusplus** 2024-02-18 16:18 UTC

**Comment by postal12** [comment] 2024-06-01 06:01
Do you know these games? When will they be compatible? Even though TouchHhle v02.2 version supports 3.0, most of the games cannot be opened. Why can you choose a better one? Thank you.
