### ISSUE TITLE
Will this application be able to be installed on v7a phones in the future?

### ISSUE THREAD

**Issue by lequangcuong123** [hikari-no-yume/touchHLE#354] opened 2024-08-28 16:37 UTC
### Describe the feature or issue.

Honestly, I really want to play those iPhone games again that I never had the chance to play again. But it's inconvenient if I can't install them on my phone

### By submitting this issue, I certify that…

- [X] I understand that linking to, discussing or asking for pirated content is not permitted, and will lead to an immediate ban.
- [X] I understand that “Abandonware” and illegal copies of free games are also pirated content.

**Comment by hikari-no-yume** [comment] 2024-08-28 16:39
Duplicate of https://github.com/touchHLE/touchHLE/issues/220.

**Closed as not planned by hikari-no-yume** 2024-08-28 16:39 UTC
Labels: duplicate
