### ISSUE TITLE
Accelerometer doesn't work on Poco F3

### ISSUE THREAD

**Issue by ahmed3110c** [hikari-no-yume/touchHLE#302] opened 2024-05-09 22:31 UTC
![Screenshot_2024-05-10-01-26-10-449_org touchhle android](https://github.com/touchHLE/touchHLE/assets/35050653/7e2dd339-acc3-402f-91b7-3cdfd1e3cdbb)
I tried both 1.0.0 and 0.7.6 versions of Crash Nitro Kart 3D on 0.2.2 version of touchhle. The accelerometer doesn't work
Device: Poco F3
Software version: Android 13 (HyperOS 1.0)

**Comment by hikari-no-yume** [comment] 2024-05-09 22:34
Duplicate of https://github.com/touchHLE/touchHLE/issues/151

**Closed as not planned by hikari-no-yume** 2024-05-09 22:34 UTC
Labels: duplicate
