### ISSUE TITLE
games not showing when my files are in the correct folder 

### ISSUE THREAD

**Issue by scarletremi** [hikari-no-yume/touchHLE#359] opened 2024-09-08 03:47 UTC
### Describe the feature or issue.

![imagem](https://github.com/user-attachments/assets/c19febc6-2345-4d42-a6c0-9f84da03eb70)
 i have the files on the correct folder but in the app it shows nothing here is the log file hope it helps 

my apologies for the previous post i didnt realize i pressed for a game report 

### By submitting this issue, I certify that…

- [X] I understand that linking to, discussing or asking for pirated content is not permitted, and will lead to an immediate ban.
- [X] I understand that “Abandonware” and illegal copies of free games are also pirated content.

**Comment by scarletremi** [comment] 2024-09-09 18:51
a kinda fix i found: if i copy the files from my downloads folder instead of using the cut feature it works not sure if someone sees this i am not sure if it will work for you but give it a try i guess

**Comment by GdGohan** [comment] 2024-09-10 11:55
Thankss
I noticed that in LineageOS 20 rom when using the cut, it took longer to move, it seems that in the normal ROM there is this bug

**Comment by hikari-no-yume** [comment] 2024-12-05 15:03
Duplicate of https://github.com/touchHLE/touchHLE/issues/393

**Closed as not planned by hikari-no-yume** 2024-12-05 15:03 UTC
