### ISSUE TITLE
Any chance for a nightly version of Android? 

### ISSUE THREAD

**Issue by GamingDucking** [hikari-no-yume/touchHLE#182] opened 2023-10-26 12:18 UTC
In my opinion, it could be easier for me to test games on Android (if i am in the go or don't have a computer to test with).

**Comment by hikari-no-yume** [comment] 2023-10-26 12:21
It would be good to have one, especially for catching regressions. I might do this eventually.

**Comment by ThanhPhuc0** [comment] 2023-10-26 14:49
It also have a white screen bugs in PowerVR GPU phones (like my Oppo A12)

**Comment by hikari-no-yume** [comment] 2023-10-26 15:34
@ThanhPhuc0 Please keep discussion on-topic. You're welcome to open a new issue for the white screen problem, but it has no relation to this issue.

**Comment by hikari-no-yume** [comment] 2024-02-23 14:53
Note: duplicate of https://github.com/hikari-no-yume/touchHLE/issues/120.

**Comment by hikari-no-yume** [comment] 2024-02-23 15:27
CI will provide Android builds as of a050b1da7c125f88c3fb8c23090f509892194ceb.

**Closed as completed by hikari-no-yume** 2024-02-23 15:27 UTC
