### ISSUE TITLE
Video/subtitles playback is not supported by the app

### ISSUE THREAD

**Issue by random-jack925** [hikari-no-yume/touchHLE#403] opened 2024-12-29 22:45 UTC
### Describe the feature or issue.

Although this seems to already be acknowledged by the developers, I would like to file this issue anyways. Video/subtitles playback is not supported by the emulator. Every time a video is meant to play in-game, the emulator skips it (on the majority of games) or crashes (on Zombie Infection). And of course this also counts for the subtitles the videos were meant to display. This is generally not an issue gameplay-wise but it is story-wise, although it is an issue gameplay-wise in some games.

### By submitting this issue, I certify that…

- [X] I understand that linking to, discussing or asking for pirated content is not permitted, and will lead to an immediate ban.
- [X] I understand that “Abandonware” and illegal copies of free games are also pirated content.

**Comment by hikari-no-yume** [comment] 2024-12-29 22:47
Duplicate of https://github.com/touchHLE/touchHLE/issues/89. Please check for an existing issue before opening a new one.

**Closed as not planned by hikari-no-yume** 2024-12-29 22:47 UTC
Labels: duplicate
