### ISSUE TITLE
Have any ideas about adding more .dylib files?

### ISSUE THREAD

**Issue by AAArisle** [hikari-no-yume/touchHLE#304] opened 2024-05-11 15:02 UTC
When I try to run another one old game on the Android version, there are some forms of warnings as follows:
> touchHLE::environment: Warning: app binary depends on unexpected dylib "/usr/lib/libz.1.dylib"
> touchHLE::environment: Warning: app binary depends on unexpected dylib "/usr/lib/libsqlite3.dylib"
> touchHLE::environment: Warning: app binary depends on unexpected dylib "/usr/lib/libicucore.A.dylib"

Of course, this game crashes. It requires iPhone OS 3.0, so I think this is like a problem caused by missing some .dynib files. If these files can be added, it may run normally.
I think adding more files will help support more old game runs. I really hope you have such thoughts.
Praise your work! Anyway, you have all contributed to the return of these old games :)
(These English are translated by machines, I hope it won't cause any trouble for your reading.)

**Comment by ciciplusplus** [comment] 2024-05-11 16:16
Hi,

This is a duplicate of an another issue https://github.com/touchHLE/touchHLE/issues/242

Basically, we cannot "just add" other .dylibs for licensing reasons.
The dylibs you have mentioned are need to be recompiled from source or re-implemented from scratch.

**Closed as not planned by ciciplusplus** 2024-05-11 16:16 UTC
