### ISSUE TITLE
Windows 10 build issue: “failed to build archive: bad archive: truncated or malformed archive”

### ISSUE THREAD

**Issue by hikari-no-yume** [hikari-no-yume/touchHLE#130] opened 2023-06-17 18:04 UTC
Seen in GitHub Actions builds on Windows:

```
error: failed to build archive: bad archive: truncated or malformed archive (long name offset characters after the '/' are not all decimal numbers: 'CXXMODWEAKSYM/' for archive member header at offset 682642)

error: could not compile `touchHLE_dynarmic_wrapper` (lib) due to previous error
```

No idea why this would happen. I'm suspecting it's not a change on our side, but rather GitHub having changed the runner image. @ciciplusplus checked and confirmed that it changed since the last passing build, from 20230517.1 to 20230612.1.

**Comment by hikari-no-yume** [comment] 2023-07-15 12:01
Oh, now they work again? Maybe it was just an issue with the image after all, and it was fixed. Nice. https://github.com/hikari-no-yume/touchHLE/actions/runs/5562037823/jobs/10160088777

**Comment by Snakeynaut** [comment] 2023-07-20 21:31
I tried building today on my windows 10 PC and am having the same issue. Any ideas to get around it?


![image](https://github.com/hikari-no-yume/touchHLE/assets/69934249/00bc5280-d810-4d8a-a4ae-97a71848a48c)

**Comment by hikari-no-yume** [comment] 2023-07-23 08:35
I don't really understand what the issue is, and it doesn't happen on my machine, so I'm not even sure how to begin debugging it.

**Comment by Snakeynaut** [comment] 2023-07-25 08:11
No worries. Since github actions works its not a super big deal.

Apparently this error is due to the way cargo builds projects, based on reading this thread: https://github.com/denoland/deno/issues/8385.

I tried running `cargo build -j1` but it resulted in the same error. I also tried reinstalling Microsoft Visual Studio and the respective C/C++ packages without any change.

It's always the touchHLE_dynarmic_wrapper v0.1.2 compilation that fails.

Heres the error with the verbose flag:


>  cargo build -v
warning: output filename collision.
The bin target `touchHLE` in package `touchHLE v0.1.2 (C:\Users\aminf\OneDrive\Desktop\iosEmu\touchHLE)` has the same output filename as the lib target `touchHLE` in package `touchHLE v0.1.2 (C:\Users\aminf\OneDrive\Desktop\iosEmu\touchHLE)`.
Colliding filename is: C:\Users\aminf\OneDrive\Desktop\iosEmu\touchHLE\target\debug\deps\touchHLE.pdb
The targets should have unique names.
Consider changing their names to be unique or compiling them separately.
This may become a hard error in the future; see <https://github.com/rust-lang/cargo/issues/6313>.
warning: output filename collision.
The bin target `touchHLE` in package `touchHLE v0.1.2 (C:\Users\aminf\OneDrive\Desktop\iosEmu\touchHLE)` has the same output filename as the lib target `touchHLE` in package `touchHLE v0.1.2 (C:\Users\aminf\OneDrive\Desktop\iosEmu\touchHLE)`.
Colliding filename is: C:\Users\aminf\OneDrive\Desktop\iosEmu\touchHLE\target\debug\touchHLE.pdb
The targets should have unique names.
Consider changing their names to be unique or compiling them separately.
This may become a hard error in the future; see <https://github.com/rust-lang/cargo/issues/6313>.
       Fresh unicode-ident v1.0.11
       Fresh cc v1.0.79
       Fresh autocfg v1.1.0
       Fresh version_check v0.9.4
       Fresh itoa v1.0.9
       Fresh cfg-if v1.0.0
       Fresh log v0.4.19
       Fresh hashbrown v0.12.3
       Fresh proc-macro2 v1.0.66
       Fresh cmake v0.1.50
       Fresh version-compare v0.1.1
       Fresh bitflags v1.3.2
       Fresh xml-rs v0.8.16
       Fresh quote v1.0.32
       Fresh winapi v0.3.9
       Fresh khronos_api v3.1.0
       Fresh ryu v1.0.15
       Fresh os_str_bytes v6.5.1
       Fresh heck v0.4.1
       Fresh syn v2.0.27
       Fresh proc-macro-error-attr v1.0.4
       Fresh syn v1.0.109
       Fresh gl_generator v0.14.0
       Fresh winapi-util v0.1.5
       Fresh atty v0.2.14
       Fresh csv-core v0.1.10
       Fresh clap_lex v0.2.4
       Fresh textwrap v0.16.0
       Fresh strsim v0.10.0
       Fresh unicode-width v0.1.10
       Fresh serde_derive v1.0.174
       Fresh thiserror-impl v1.0.44
       Fresh proc-macro-error v1.0.4
       Fresh termcolor v1.2.0
       Fresh time-core v0.1.1
       Fresh once_cell v1.18.0
       Fresh libc v0.2.147
       Fresh anyhow v1.0.72
       Fresh getopts v0.2.21
       Fresh ansi_term v0.12.1
       Fresh byteorder v1.4.3
       Fresh adler v1.0.2
       Fresh thiserror v1.0.44
       Fresh clap_derive v3.2.25
       Fresh time-macros v0.2.10
       Fresh memchr v2.5.0
       Fresh miniz_oxide v0.7.1
       Fresh ttf-parser v0.15.2
       Fresh camino v1.1.6
       Fresh semver v1.0.18
       Fresh serde_json v1.0.103
       Fresh cargo-platform v0.1.3
       Fresh clap v3.2.25
       Fresh toml v0.5.11
       Fresh csv v1.2.2
       Fresh crc32fast v1.3.2
       Fresh time v0.3.23
       Fresh lazy_static v1.4.0
       Fresh safemem v0.3.3
       Fresh indexmap v1.9.3
       Fresh cargo_metadata v0.15.4
       Fresh flate2 v1.0.26
       Fresh line-wrap v0.1.1
       Fresh quick-xml v0.29.0
       Fresh owned_ttf_parser v0.15.2
       Fresh serde v1.0.174
       Fresh sdl2-sys v0.35.2 (https://github.com/hikari-no-yume/rust-sdl2.git?tag=touchHLE-2#15c58be7)
       Fresh ab_glyph_rasterizer v0.1.8
       Fresh base64 v0.21.2
       Fresh uuid v1.4.1
       Fresh touchHLE_gl_bindings v0.1.2 (C:\Users\aminf\OneDrive\Desktop\iosEmu\touchHLE\src\gles\gl_bindings)
       Fresh touchHLE_stb_image_wrapper v0.1.2 (C:\Users\aminf\OneDrive\Desktop\iosEmu\touchHLE\src\image\stb_image_wrapper)
       Fresh cargo-license v0.5.1
       Fresh touchHLE_pvrt_decompress_wrapper v0.1.2 (C:\Users\aminf\OneDrive\Desktop\iosEmu\touchHLE\src\image\pvrt_decompress_wrapper)
       Fresh sdl2 v0.35.2 (https://github.com/hikari-no-yume/rust-sdl2.git?tag=touchHLE-2#15c58be7)
       Fresh plist v1.5.0
       Fresh mach_object v0.1.17
       Fresh zip v0.6.6
       Fresh touchHLE_dr_mp3_wrapper v0.1.2 (C:\Users\aminf\OneDrive\Desktop\iosEmu\touchHLE\src\audio\dr_mp3_wrapper)
       Fresh rusttype v0.9.3
   Compiling touchHLE_dynarmic_wrapper v0.1.2 (C:\Users\aminf\OneDrive\Desktop\iosEmu\touchHLE\src\cpu\dynarmic_wrapper)
       Fresh touchHLE_openal_soft_wrapper v0.1.2 (C:\Users\aminf\OneDrive\Desktop\iosEmu\touchHLE\src\audio\openal_soft_wrapper)
       Fresh caf v0.1.0
       Fresh hound v3.5.0
     Running `rustc --crate-name touchHLE_dynarmic_wrapper --edition=2021 'src\cpu\dynarmic_wrapper\lib.rs' --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 -C metadata=cc082a7eef36b8fe -C extra-filename=-cc082a7eef36b8fe --out-dir 'C:\Users\aminf\OneDrive\Desktop\iosEmu\touchHLE\target\debug\deps' -C 'incremental=C:\Users\aminf\OneDrive\Desktop\iosEmu\touchHLE\target\debug\incremental' -L 'dependency=C:\Users\aminf\OneDrive\Desktop\iosEmu\touchHLE\target\debug\deps' -L 'native=C:\Users\aminf\OneDrive\Desktop\iosEmu\touchHLE\target\debug\build\touchHLE_dynarmic_wrapper-e8f9aed518859b03\out\lib' -L 'native=C:\Users\aminf\OneDrive\Desktop\iosEmu\touchHLE\target\debug\build\touchHLE_dynarmic_wrapper-e8f9aed518859b03\out\lib64' -L 'native=C:\Users\aminf\OneDrive\Desktop\iosEmu\touchHLE\target\debug\build\touchHLE_dynarmic_wrapper-e8f9aed518859b03\out\build/externals/fmt\Debug' -L 'native=C:\Users\aminf\OneDrive\Desktop\iosEmu\touchHLE\target\debug\build\touchHLE_dynarmic_wrapper-e8f9aed518859b03\out\build/externals/mcl/src\Debug' -L 'native=C:\Users\aminf\OneDrive\Desktop\iosEmu\touchHLE\target\debug\build\touchHLE_dynarmic_wrapper-e8f9aed518859b03\out\build/externals/zydis\Debug' -L 'native=C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.36.32532\atlmfc\lib\x64' -L 'native=C:\Users\aminf\OneDrive\Desktop\iosEmu\touchHLE\target\debug\build\touchHLE_dynarmic_wrapper-e8f9aed518859b03\out' -l static=dynarmic -l static=fmtd -l static=mcl -l static=Zydis -l static=dynarmic_wrapper`
error: failed to build archive: bad archive: truncated or malformed archive (long name offset characters after the '/' are not all decimal numbers: 'CXXMODWEAKSYM/' for archive member header at offset 682372)

error: could not compile `touchHLE_dynarmic_wrapper` (lib) due to previous error

Caused by:
  process didn't exit successfully: `rustc --crate-name touchHLE_dynarmic_wrapper --edition=2021 'src\cpu\dynarmic_wrapper\lib.rs' --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 -C metadata=cc082a7eef36b8fe -C extra-filename=-cc082a7eef36b8fe --out-dir 'C:\Users\aminf\OneDrive\Desktop\iosEmu\touchHLE\target\debug\deps' -C 'incremental=C:\Users\aminf\OneDrive\Desktop\iosEmu\touchHLE\target\debug\incremental' -L 'dependency=C:\Users\aminf\OneDrive\Desktop\iosEmu\touchHLE\target\debug\deps' -L 'native=C:\Users\aminf\OneDrive\Desktop\iosEmu\touchHLE\target\debug\build\touchHLE_dynarmic_wrapper-e8f9aed518859b03\out\lib' -L 'native=C:\Users\aminf\OneDrive\Desktop\iosEmu\touchHLE\target\debug\build\touchHLE_dynarmic_wrapper-e8f9aed518859b03\out\lib64' -L 'native=C:\Users\aminf\OneDrive\Desktop\iosEmu\touchHLE\target\debug\build\touchHLE_dynarmic_wrapper-e8f9aed518859b03\out\build/externals/fmt\Debug' -L 'native=C:\Users\aminf\OneDrive\Desktop\iosEmu\touchHLE\target\debug\build\touchHLE_dynarmic_wrapper-e8f9aed518859b03\out\build/externals/mcl/src\Debug' -L 'native=C:\Users\aminf\OneDrive\Desktop\iosEmu\touchHLE\target\debug\build\touchHLE_dynarmic_wrapper-e8f9aed518859b03\out\build/externals/zydis\Debug' -L 'native=C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.36.32532\atlmfc\lib\x64' -L 'native=C:\Users\aminf\OneDrive\Desktop\iosEmu\touchHLE\target\debug\build\touchHLE_dynarmic_wrapper-e8f9aed518859b03\out' -l static=dynarmic -l static=fmtd -l static=mcl -l static=Zydis -l static=dynarmic_wrapper` (exit code: 1)
  
  
EDIT: I think the problem may be with the way my system is configured. I'll try fully uninstalling Visual Studio and relying on mingw for C/C++ compilation

**Comment by Snakeynaut** [comment] 2023-08-18 00:15
I was finally able to build the project without any errors.

What ended up working for me was the following steps:
1. Completely uninstall Microsoft Visual Studio Community (the one i use) and all of the components I had installed.
2. Uninstall Cmake (which I had previously installed from [here](https://cmake.org/))
3. Uninstall MSYS and MINGW.
4. Redownload MSVC with the components installed by @hikari-no-yume in #109 (10th post), except I did not download the Cmake provided by MSVC
5. Reinstall Cmake from https://cmake.org/
6. Set my rustup default toolchain to msvc
7. Build

After this, my build finally worked.

I think the issue arose because I previously had both versions of CMAKE installed at the same time which resulted in some conflict.

**Comment by hikari-no-yume** [comment] 2023-08-18 15:08
Ah, yeah, that could be it. I'm not sure which setup I have, but I don't think I installed two versions of CMake. Thanks for investigating!

**Comment by 999pingGG** [comment] 2023-08-28 19:07
I'm currently having the same issue. I am just getting started with Rust, no idea on this either. I just want to see if I can learn Rust and help getting Bike or Die running in this emulator. I don't want to reinstall the wholeass MSVC in this machine, so I will wait until I can use my Linux rig later today.

**Comment by ciciplusplus** [comment] 2024-02-18 16:24
Closing as we don't have this issue anymore on the CI

**Closed as completed by ciciplusplus** 2024-02-18 16:24 UTC
Labels: build issue on supported platform
